apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  # The externalTrafficPolicy with value Local means that requests should only be proxied to local endpoints. 
  # It will never forward traffic to other nodes preserving the original source IP address.
  externalTrafficPolicy: Local
  ports:
   - port: 80
  selector:
    service: ambassador