apiVersion: v1
kind: Service
metadata:
  name: envoy-pod-service
  labels:
    app: myapp-envoy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: myapp-envoy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-pod
  labels:
    app: myapp-envoy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-envoy
  template:
    metadata:
      labels:
        app: myapp-envoy
    spec:
      containers:
      - name: myapp-envoy
        image: vitorcmonteiro/article-04_envoy:1
        resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: envoy-admin
          containerPort: 9901