--- 
apiVersion: extensions/v1beta1 
kind: Deployment
metadata: 
  name: grafana   
  namespace: default 
spec: 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: grafana 
        component: core
    spec: 
      containers: 
      - image: grafana/grafana:6.2.0 
        name: grafana-core 
        imagePullPolicy: IfNotPresent 
        resources: 
          limits: 
            cpu: 100m 
            memory: 100Mi 
          requests: 
            cpu: 100m 
            memory: 100Mi 
        env: 
          - name: GR_SERVER_ROOT_URL 
            value: {{AMBASSADOR_IP}}/grafana 
          - name: GF_AUTH_BASIC_ENABLED 
            value: "true" 
          - name: GF_AUTH_ANONYMOUS_ENABLED 
            value: "false" 
        readinessProbe: 
          httpGet: 
            path: /login 
            port: 3000 
        volumeMounts: 
        - name: grafana-persistent-storage 
          mountPath: /var 
      volumes: 
      - name: grafana-persistent-storage 
        emptyDir: {}