apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access": "proxy",
                "editable": true,
                "name": "kube-state-metrics",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://kube-state-metrics.kube-system.svc.cluster.local:8080/metrics",
                "version": 1
            }
        ]
    }