apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    type: restapi
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      name: api-template
      labels:
        app: api
    spec:
      containers:
      - name: flask-api
        image: vitorcmonteiro/article-04_flask-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 5000
  sessionAffinity: None
